import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile, link, unlink, rmdir } from 'node:fs/promises';
import path from 'node:path';

export const ROUTING_CANDIDATE_SCHEMA = 'celestan-routing-policy-candidate-v1';
export const ROUTING_CONSOLIDATION_SCHEMA = 'celestan-routing-policy-consolidation-v1';
export const ROUTING_REVIEW_SCHEMA = 'celestan-routing-policy-review-v1';
export const ROUTING_SIGNAL_SCHEMA = 'celestan-future-routing-signal-v1';
const SHA = /^[a-f0-9]{64}$/;
const stable = value => Array.isArray(value) ? `[${value.map(stable).join(',')}]` : value && typeof value === 'object' ? `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}` : JSON.stringify(value);
const digest = value => createHash('sha256').update(stable(value)).digest('hex');
const safe = (value, name, max = 240) => { if (typeof value !== 'string' || !value.trim() || value.length > max || /[\0\r\n]/.test(value)) throw Error(`${name} must be a bounded safe string`); return value; };
const obj = (value, name) => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw Error(`${name} must be an object`); return value; };
const exact = (value, keys, name) => { obj(value, name); const allowed = new Set(keys); if (Object.keys(value).some(key => !allowed.has(key))) throw Error(`${name} has unknown or forbidden fields`); };
const iso = (value, name) => { safe(value, name, 64); if (value !== new Date(value).toISOString()) throw Error(`${name} must be canonical ISO timestamp`); return value; };
const forbidden = /semanticEvidenceEnvelope|modelAttribution|modelRuntimeTelemetry|structuralContext|executionDistribution|rawEvidence|evidenceReferences|telemetryReferences|raw|telemetry|attribution|stdout|stderr|headers|body|stack|toolArguments|toolOutput/i;
function rejectForbidden(value, where = 'durable observation') { if (!value || typeof value !== 'object') return; for (const [key, child] of Object.entries(value)) { if (forbidden.test(key)) throw Error(`${where} contains forbidden field ${key}`); rejectForbidden(child, `${where}.${key}`); } }
function uniqueStrings(value, name, hashes = false, max = 180) { if (!Array.isArray(value) || !value.length || new Set(value).size !== value.length) throw Error(`${name} must be non-empty and unique`); value.forEach(id => hashes ? (!SHA.test(id) && (() => { throw Error(`${name} contains an invalid hash`); })()) : safe(id, name, max)); return [...value].sort(); }
function classification(value) {
  const c = Object.fromEntries(['subject', 'direction', 'proposedEffect', 'scopeLimit', 'citedClaimIds'].map(key => [key, value[key]]));
  exact(c, ['subject', 'direction', 'proposedEffect', 'scopeLimit', 'citedClaimIds'], 'routing classification');
  exact(c.subject, ['model', 'role', 'taskClass'], 'subject');
  safe(c.subject.model, 'subject.model', 300); safe(c.subject.role, 'subject.role', 160); safe(c.subject.taskClass, 'subject.taskClass', 160);
  if (!c.subject.model.includes('/')) throw Error('subject.model must be provider-qualified');
  if (!['positive', 'negative'].includes(c.direction) || !['lower-preference', 'restore-default'].includes(c.proposedEffect) || (c.direction === 'negative') !== (c.proposedEffect === 'lower-preference')) throw Error('direction and proposedEffect are inconsistent');
  exact(c.scopeLimit, ['globalDemotion', 'unrelatedWorkUnassessed', 'boundedWorkerUsePermitted', 'project'], 'scopeLimit');
  if (c.scopeLimit.globalDemotion !== false || c.scopeLimit.unrelatedWorkUnassessed !== true || c.scopeLimit.boundedWorkerUsePermitted !== true) throw Error('scopeLimit safety constraints are invalid');
  if (c.scopeLimit.project !== undefined) safe(c.scopeLimit.project, 'scopeLimit.project', 180);
  const citedClaimIds = uniqueStrings(c.citedClaimIds, 'citedClaimIds');
  return { subject: { ...c.subject }, direction: c.direction, proposedEffect: c.proposedEffect, scopeLimit: { ...c.scopeLimit }, citedClaimIds };
}
export function validateDurableObservation(value) {
  rejectForbidden(value); exact(value, ['observation_id', 'schema', 'evidenceId', 'physicalExecutionId', 'observation', 'provenance'], 'durable observation');
  if (value.schema !== 'celestan-semantic-observation-v1') throw Error('durable observation schema is invalid');
  safe(value.observation_id, 'observation_id', 180); safe(value.evidenceId, 'evidenceId', 180); if (value.physicalExecutionId !== null) safe(value.physicalExecutionId, 'physicalExecutionId', 180);
  exact(value.observation, ['schema', 'envelopeId', 'observations'], 'observation'); if (value.observation.schema !== 'celestan-semantic-observation-v1') throw Error('observation schema is invalid'); safe(value.observation.envelopeId, 'envelopeId', 180);
  if (!Array.isArray(value.observation.observations) || !value.observation.observations.length) throw Error('observations must be non-empty');
  const claims = new Set(); for (const claim of value.observation.observations) { exact(claim, ['claimId', 'statement', 'interpretation', 'sourceClass', 'claimType', 'supportSourceIds'], 'claim'); safe(claim.claimId, 'claim.claimId', 160); safe(claim.statement, 'claim.statement', 1000); safe(claim.interpretation, 'claim.interpretation', 1000); safe(claim.sourceClass, 'claim.sourceClass', 160); safe(claim.claimType, 'claim.claimType', 160); uniqueStrings(claim.supportSourceIds, 'supportSourceIds'); if (claims.has(claim.claimId)) throw Error('claimId must be unique'); claims.add(claim.claimId); }
  exact(value.provenance, ['evidenceId', 'hash'], 'provenance'); if (value.provenance.evidenceId !== value.evidenceId || !SHA.test(value.provenance.hash)) throw Error('observation provenance is invalid'); return value;
}
export function deriveRoutingPolicyCandidate(observation, proposal) {
  validateDurableObservation(observation); const c = classification(proposal); const claims = new Set(observation.observation.observations.map(x => x.claimId)); if (c.citedClaimIds.some(id => !claims.has(id))) throw Error('citedClaimIds contains an unknown claim');
  const body = { observationId: observation.observation_id, observationEvidenceHash: observation.provenance.hash, evidenceId: observation.evidenceId, envelopeId: observation.observation.envelopeId, ...c }; const contentHash = digest(body);
  return { schema: ROUTING_CANDIDATE_SCHEMA, candidateId: `rpc_${contentHash.slice(0, 32)}`, contentHash, ...body, status: 'review-required' };
}
export function validateRoutingPolicyCandidate(value) {
  exact(value, ['schema', 'candidateId', 'contentHash', 'observationId', 'observationEvidenceHash', 'evidenceId', 'envelopeId', 'subject', 'direction', 'proposedEffect', 'scopeLimit', 'citedClaimIds', 'status'], 'candidate');
  if (value.schema !== ROUTING_CANDIDATE_SCHEMA || value.status !== 'review-required' || !SHA.test(value.contentHash) || !SHA.test(value.observationEvidenceHash)) throw Error('candidate is invalid'); safe(value.candidateId, 'candidateId', 180); safe(value.observationId, 'observationId', 180); safe(value.evidenceId, 'evidenceId', 180); safe(value.envelopeId, 'envelopeId', 180); classification(value);
  const body = { observationId: value.observationId, observationEvidenceHash: value.observationEvidenceHash, evidenceId: value.evidenceId, envelopeId: value.envelopeId, ...classification(value) }; if (value.contentHash !== digest(body) || value.candidateId !== `rpc_${value.contentHash.slice(0, 32)}`) throw Error('candidate ID or contentHash is not deterministic'); return value;
}
function findingFromCandidates(cs) {
  const first = cs[0]; const c = classification(first); const f = { ...c, candidateIds: uniqueStrings(cs.map(x => x.candidateId), 'candidateIds'), observationIds: uniqueStrings(cs.map(x => x.observationId), 'observationIds'), observationEvidenceHashes: uniqueStrings(cs.map(x => x.observationEvidenceHash), 'observationEvidenceHashes', true), evidenceIds: uniqueStrings(cs.map(x => x.evidenceId), 'evidenceIds'), envelopeIds: uniqueStrings(cs.map(x => x.envelopeId), 'envelopeIds'), status: 'review-required' };
  const contentHash = digest(f); return { findingId: `rf_${contentHash.slice(0, 32)}`, contentHash, ...f };
}
export function consolidateRoutingPolicyCandidates(candidates) {
  if (!Array.isArray(candidates) || !candidates.length) throw Error('candidates must be non-empty'); candidates.forEach(validateRoutingPolicyCandidate);
  const groups = new Map(); for (const candidate of candidates) { const key = stable({ ...candidate.subject, project: candidate.scopeLimit.project ?? null, direction: candidate.direction, proposedEffect: candidate.proposedEffect }); const list = groups.get(key) || []; list.push(candidate); groups.set(key, list); }
  const findings = [...groups.values()].map(findingFromCandidates).sort((a, b) => a.findingId.localeCompare(b.findingId)); const body = { findings }; const contentHash = digest(body); return { schema: ROUTING_CONSOLIDATION_SCHEMA, consolidationId: `rcon_${contentHash.slice(0, 32)}`, contentHash, ...body, status: 'review-required' };
}
function validateFinding(value) { exact(value, ['findingId', 'contentHash', 'subject', 'direction', 'proposedEffect', 'scopeLimit', 'candidateIds', 'observationIds', 'observationEvidenceHashes', 'evidenceIds', 'envelopeIds', 'citedClaimIds', 'status'], 'finding'); classification(value); uniqueStrings(value.candidateIds, 'candidateIds'); uniqueStrings(value.observationIds, 'observationIds'); uniqueStrings(value.observationEvidenceHashes, 'observationEvidenceHashes', true); uniqueStrings(value.evidenceIds, 'evidenceIds'); uniqueStrings(value.envelopeIds, 'envelopeIds'); if (value.status !== 'review-required' || !SHA.test(value.contentHash) || value.contentHash !== digest({ subject: value.subject, direction: value.direction, proposedEffect: value.proposedEffect, scopeLimit: value.scopeLimit, citedClaimIds: value.citedClaimIds, candidateIds: value.candidateIds, observationIds: value.observationIds, observationEvidenceHashes: value.observationEvidenceHashes, evidenceIds: value.evidenceIds, envelopeIds: value.envelopeIds, status: value.status }) || value.findingId !== `rf_${value.contentHash.slice(0, 32)}`) throw Error('finding hash or ID is invalid'); return value; }
export function validateRoutingPolicyConsolidation(value) { exact(value, ['schema', 'consolidationId', 'contentHash', 'findings', 'status'], 'consolidation'); if (value.schema !== ROUTING_CONSOLIDATION_SCHEMA || value.status !== 'review-required' || !Array.isArray(value.findings) || !value.findings.length) throw Error('consolidation is invalid'); value.findings.forEach(validateFinding); if (value.contentHash !== digest({ findings: value.findings }) || value.consolidationId !== `rcon_${value.contentHash.slice(0, 32)}`) throw Error('consolidation hash or ID is not deterministic'); return value; }
export function validateRoutingPolicyReview(value) {
  exact(value, ['schema', 'reviewId', 'contentHash', 'consolidationId', 'findingId', 'candidateIds', 'observationIds', 'observationEvidenceHashes', 'evidenceIds', 'envelopeIds', 'citedClaimIds', 'decision', 'reviewerId', 'rationale', 'reviewedAt', 'supersedesSignalIds', 'supersessionMode', 'status', 'signal'], 'review');
  if (value.schema !== ROUTING_REVIEW_SCHEMA || value.status !== 'reviewed' || !['accept', 'reject', 'defer'].includes(value.decision) || !SHA.test(value.contentHash)) throw Error('review is invalid');
  safe(value.consolidationId, 'consolidationId', 180); safe(value.findingId, 'findingId', 180); safe(value.reviewerId, 'reviewerId', 180); safe(value.rationale, 'rationale', 2000); iso(value.reviewedAt, 'reviewedAt');
   uniqueStrings(value.candidateIds, 'candidateIds'); uniqueStrings(value.observationIds, 'observationIds'); uniqueStrings(value.observationEvidenceHashes, 'observationEvidenceHashes', true); uniqueStrings(value.evidenceIds, 'evidenceIds'); uniqueStrings(value.envelopeIds, 'envelopeIds'); uniqueStrings(value.citedClaimIds, 'citedClaimIds');
  if (!Array.isArray(value.supersedesSignalIds) || new Set(value.supersedesSignalIds).size !== value.supersedesSignalIds.length) throw Error('supersedesSignalIds must be unique');
  if (!['restore', 'narrow', 'replace'].includes(value.supersessionMode)) throw Error('invalid supersessionMode'); if (value.decision === 'accept' && !value.signal) throw Error('accepted review must contain signal'); if (value.decision !== 'accept' && value.signal) throw Error('non-accepted review cannot contain signal');
  const body = { consolidationId: value.consolidationId, findingId: value.findingId, candidateIds: value.candidateIds, observationIds: value.observationIds, observationEvidenceHashes: value.observationEvidenceHashes, evidenceIds: value.evidenceIds, envelopeIds: value.envelopeIds, citedClaimIds: value.citedClaimIds, decision: value.decision, reviewerId: value.reviewerId, rationale: value.rationale, reviewedAt: value.reviewedAt, supersedesSignalIds: value.supersedesSignalIds, supersessionMode: value.supersessionMode };
   if (value.contentHash !== digest(body) || value.reviewId !== `rpr_${value.contentHash.slice(0, 32)}`) throw Error('review hash or ID is invalid'); if (value.signal) { validateRoutingPolicySignal(value.signal); const expected = signalBody({ subject: value.signal.subject, direction: value.signal.direction, proposedEffect: value.signal.proposedEffect, scopeLimit: value.signal.scopeLimit, candidateIds: value.candidateIds, observationIds: value.observationIds, observationEvidenceHashes: value.observationEvidenceHashes, evidenceIds: value.evidenceIds, envelopeIds: value.envelopeIds, citedClaimIds: value.citedClaimIds }, value); if (stable(Object.fromEntries(Object.keys(expected).map(key => [key, value.signal[key]]))) !== stable(expected)) throw Error('embedded signal lineage is invalid'); } return value;
}
export function createRoutingPolicyReview(consolidationOrFinding, findingOrInput, maybeInput) {
  const consolidation = maybeInput ? consolidationOrFinding : null; const finding = maybeInput ? findingOrInput : consolidationOrFinding; const input = maybeInput || findingOrInput; validateFinding(finding); if (consolidation) { validateRoutingPolicyConsolidation(consolidation); if (!consolidation.findings.some(x => x.findingId === finding.findingId)) throw Error('finding is not in consolidation'); }
  exact(input, ['decision', 'reviewerId', 'rationale', 'reviewedAt', 'supersedesSignalIds', 'supersessionMode'], 'review input'); if (!['accept', 'reject', 'defer'].includes(input.decision)) throw Error('invalid decision'); safe(input.reviewerId, 'reviewerId', 180); safe(input.rationale, 'rationale', 2000); iso(input.reviewedAt, 'reviewedAt'); if (!Array.isArray(input.supersedesSignalIds) || new Set(input.supersedesSignalIds).size !== input.supersedesSignalIds.length) throw Error('supersedesSignalIds must be an array'); input.supersedesSignalIds.forEach(id => safe(id, 'supersedesSignalId', 180)); if (!['restore', 'narrow', 'replace'].includes(input.supersessionMode)) throw Error('invalid supersessionMode');
  const body = { consolidationId: consolidation?.consolidationId, findingId: finding.findingId, candidateIds: finding.candidateIds, observationIds: finding.observationIds, observationEvidenceHashes: finding.observationEvidenceHashes, evidenceIds: finding.evidenceIds, envelopeIds: finding.envelopeIds, citedClaimIds: finding.citedClaimIds, ...input }; if (!body.consolidationId) throw Error('consolidationId is required'); const contentHash = digest(body); return { schema: ROUTING_REVIEW_SCHEMA, reviewId: `rpr_${contentHash.slice(0, 32)}`, contentHash, ...body, status: 'reviewed' };
}
function signalBody(f, r) { return { schema: ROUTING_SIGNAL_SCHEMA, status: 'active', reviewId: r.reviewId, subject: f.subject, direction: f.direction, proposedEffect: f.proposedEffect, scopeLimit: f.scopeLimit, candidateIds: f.candidateIds, observationIds: f.observationIds, observationEvidenceHashes: f.observationEvidenceHashes, evidenceIds: f.evidenceIds, envelopeIds: f.envelopeIds, citedClaimIds: f.citedClaimIds, supersedesSignalIds: r.supersedesSignalIds, supersessionMode: r.supersessionMode, acceptedAt: r.reviewedAt, consolidationId: r.consolidationId, findingId: r.findingId };
}
export function createRoutingPolicySignal(f, r) { const body = signalBody(f, r); const contentHash = digest(body); return { ...body, signalId: `rps_${contentHash.slice(0, 32)}`, contentHash }; }
export function validateRoutingPolicySignal(value) { const keys = ['schema', 'signalId', 'contentHash', 'status', 'subject', 'direction', 'proposedEffect', 'scopeLimit', 'reviewId', 'consolidationId', 'findingId', 'candidateIds', 'observationIds', 'observationEvidenceHashes', 'evidenceIds', 'envelopeIds', 'citedClaimIds', 'supersedesSignalIds', 'supersessionMode', 'acceptedAt']; exact(value, keys, 'signal'); if (value.schema !== ROUTING_SIGNAL_SCHEMA || value.status !== 'active' || !SHA.test(value.contentHash)) throw Error('signal is invalid'); classification(value); safe(value.reviewId, 'reviewId', 180); safe(value.consolidationId, 'consolidationId', 180); safe(value.findingId, 'findingId', 180); uniqueStrings(value.candidateIds, 'candidateIds'); uniqueStrings(value.observationIds, 'observationIds'); uniqueStrings(value.observationEvidenceHashes, 'observationEvidenceHashes', true); uniqueStrings(value.evidenceIds, 'evidenceIds'); uniqueStrings(value.envelopeIds, 'envelopeIds'); if (!Array.isArray(value.supersedesSignalIds) || new Set(value.supersedesSignalIds).size !== value.supersedesSignalIds.length) throw Error('supersedesSignalIds must be unique'); value.supersedesSignalIds.forEach(id => safe(id, 'supersedesSignalId', 180)); if (!['restore', 'narrow', 'replace'].includes(value.supersessionMode)) throw Error('invalid supersessionMode'); if (value.direction === 'positive' && value.proposedEffect === 'restore-default' && (!value.supersedesSignalIds.length || !['restore', 'narrow'].includes(value.supersessionMode))) throw Error('positive restore requires supersession'); if (value.direction === 'negative' && value.proposedEffect === 'lower-preference' && value.supersessionMode !== 'replace') throw Error('negative signal requires replace mode'); iso(value.acceptedAt, 'acceptedAt'); if (value.contentHash !== digest(Object.fromEntries(keys.filter(k => !['signalId', 'contentHash'].includes(k)).map(k => [k, value[k]]))) || value.signalId !== `rps_${value.contentHash.slice(0, 32)}`) throw Error('signal hash or ID is not deterministic'); return value; }

export class RoutingPolicyStore {
  constructor(root, { authorizedReviewerIds } = {}) { if (!Array.isArray(authorizedReviewerIds) || !authorizedReviewerIds.length || new Set(authorizedReviewerIds).size !== authorizedReviewerIds.length) throw Error('authorizedReviewerIds must be non-empty'); authorizedReviewerIds.forEach(id => safe(id, 'authorizedReviewerId')); this.root = root; this.authorizedReviewerIds = new Set(authorizedReviewerIds); this.dirs = ['observations', 'candidates', 'consolidations', 'reviews']; }
  async init() { await Promise.all(this.dirs.map(d => mkdir(path.join(this.root, d), { recursive: true }))); }
  file(kind, id) { return path.join(this.root, kind, `${Buffer.from(id).toString('hex')}.json`); }
  async put(kind, id, value, validator) { await this.init(); validator(value); const target = this.file(kind, id); try { const old = JSON.parse(await readFile(target, 'utf8')); validator(old); if (stable(old) !== stable(value)) throw Error('Conflicting immutable content'); return { status: 'duplicate', value: old }; } catch (error) { if (error.code !== 'ENOENT') throw error; } const temp = `${target}.${process.pid}.${Math.random().toString(16).slice(2)}.tmp`; await writeFile(temp, JSON.stringify(value, null, 2) + '\n', { flag: 'wx' }); try { await link(temp, target); } catch (error) { if (error.code !== 'EEXIST') throw error; const old = JSON.parse(await readFile(target, 'utf8')); validator(old); if (stable(old) !== stable(value)) throw Error('Conflicting immutable content'); return { status: 'duplicate', value: old }; } finally { await unlink(temp).catch(() => {}); } return { status: 'created', value }; }
  async get(kind, id) { try { const value = JSON.parse(await readFile(this.file(kind, id), 'utf8')); this.validateKind(kind, id, value); if (kind === 'reviews') await this.validateReviewLineage(value); return value; } catch (error) { if (error.code === 'ENOENT') return undefined; throw error; } }
  async all(kind) { await this.init(); const files = await readdir(path.join(this.root, kind)); return Promise.all(files.filter(x => x.endsWith('.json')).map(async file => { const id = Buffer.from(file.slice(0, -5), 'hex').toString(); const value = JSON.parse(await readFile(path.join(this.root, kind, file), 'utf8')); this.validateKind(kind, id, value); if (kind === 'reviews') await this.validateReviewLineage(value); return value; })); }
  validateKind(kind, id, value) { const validators = { observations: validateDurableObservation, candidates: validateRoutingPolicyCandidate, consolidations: validateRoutingPolicyConsolidation, reviews: validateRoutingPolicyReview }; validators[kind](value); if (kind === 'reviews' && !this.authorizedReviewerIds.has(value.reviewerId)) throw Error('stored reviewer is unauthorized'); const actual = { observations: value.observation_id, candidates: value.candidateId, consolidations: value.consolidationId, reviews: value.reviewId }[kind]; if (actual !== id) throw Error('filename-ID binding is invalid'); }
  async validateReviewLineage(review) { const consolidation = await this.get('consolidations', review.consolidationId); const finding = consolidation?.findings.find(value => value.findingId === review.findingId); if (!finding) throw Error('stored review finding is missing'); for (const key of ['candidateIds', 'observationIds', 'observationEvidenceHashes', 'evidenceIds', 'envelopeIds', 'citedClaimIds']) if (stable(finding[key]) !== stable(review[key])) throw Error('stored review lineage mismatch'); if (review.signal && stable(review.signal) !== stable(createRoutingPolicySignal(finding, review))) throw Error('stored embedded signal lineage mismatch'); }
  appendObservation(value) { return this.put('observations', value.observation_id, value, validateDurableObservation); }
  async appendCandidate(value) { const observation = await this.get('observations', value.observationId); if (!observation) throw Error('candidate observation is missing'); if (value.evidenceId !== observation.evidenceId || value.envelopeId !== observation.observation.envelopeId || value.observationEvidenceHash !== observation.provenance.hash || value.citedClaimIds.some(id => !observation.observation.observations.some(c => c.claimId === id))) throw Error('candidate observation lineage mismatch'); return this.put('candidates', value.candidateId, value, validateRoutingPolicyCandidate); }
  async appendConsolidation(value) { validateRoutingPolicyConsolidation(value); const candidates = []; for (const finding of value.findings) for (const id of finding.candidateIds) candidates.push(await this.get('candidates', id)); if (candidates.some(x => !x)) throw Error('consolidation candidate is missing'); if (stable(consolidateRoutingPolicyCandidates(candidates)) !== stable(value)) throw Error('consolidation does not match stored candidates'); return this.put('consolidations', value.consolidationId, value, validateRoutingPolicyConsolidation); }
   async lock() { const lock = path.join(this.root, '.activation.lock'); for (let attempt = 0; attempt < 100; attempt++) { try { await mkdir(lock); return async () => { await rmdir(lock); }; } catch { await new Promise(resolve => setTimeout(resolve, 5)); } } throw Error('activation lock is present; refusing activation'); }
   async appendReview(review) { if (!this.authorizedReviewerIds.has(review.reviewerId)) throw Error('reviewer is unauthorized'); const consolidation = await this.get('consolidations', review.consolidationId); const finding = consolidation?.findings.find(x => x.findingId === review.findingId); if (!finding) throw Error('review finding is missing'); for (const key of ['candidateIds', 'observationIds', 'observationEvidenceHashes', 'evidenceIds', 'envelopeIds', 'citedClaimIds']) if (stable(finding[key]) !== stable(review[key])) throw Error('review lineage mismatch'); if (review.decision === 'accept') { const signal = createRoutingPolicySignal(finding, review); if (review.signal && stable(review.signal) !== stable(signal)) throw Error('embedded signal lineage is invalid'); review = { ...review, signal }; } validateRoutingPolicyReview(review); const release = await this.lock(); try { const existing = await this.get('reviews', review.reviewId); if (existing) { if (stable(existing) !== stable(review)) throw Error('Conflicting immutable content'); return { status: 'duplicate', value: existing }; } if (review.decision === 'accept') await this.checkSupersession(review.signal); return await this.put('reviews', review.reviewId, review, validateRoutingPolicyReview); } finally { await release(); } }
  async checkSupersession(signal) { const active = await this.activeSignals(); const targets = signal.supersedesSignalIds.map(id => active.find(x => x.signalId === id)); if (targets.some(x => !x)) throw Error('supersession target is missing or inactive'); const sameIds = (left, right) => stable([...left].sort()) === stable([...right].sort()); const dependents = target => active.filter(value => value.supersessionMode === 'narrow' && value.supersedesSignalIds.includes(target.signalId)); if (signal.direction === 'positive') { if (!targets.length) throw Error('positive signal cannot have empty supersession'); if (signal.supersessionMode === 'restore') { const primary = targets.filter(target => target.direction === 'negative' && stable(target.subject) === stable(signal.subject) && stable(target.scopeLimit) === stable(signal.scopeLimit)); if (primary.length !== 1 || !sameIds(signal.supersedesSignalIds, [primary[0].signalId, ...dependents(primary[0]).map(value => value.signalId)])) throw Error('restore target is incompatible or has unsuperseded narrow dependents'); } else if (signal.supersessionMode === 'narrow') { if (targets.length !== 1 || targets[0].direction !== 'negative' || targets[0].scopeLimit.project !== undefined || signal.scopeLimit.project === undefined || stable(targets[0].subject) !== stable(signal.subject)) throw Error('narrow target is incompatible'); } else throw Error('invalid positive supersession mode'); } else if (signal.supersessionMode === 'replace') { if (targets.length) { const primary = targets.filter(target => stable(target.subject) === stable(signal.subject) && stable(target.scopeLimit) === stable(signal.scopeLimit) && target.direction === signal.direction && target.proposedEffect === signal.proposedEffect); if (primary.length !== 1 || !sameIds(signal.supersedesSignalIds, [primary[0].signalId, ...dependents(primary[0]).map(value => value.signalId)])) throw Error('replace target is incompatible or has unsuperseded narrow dependents'); } } else if (signal.supersedesSignalIds.length || signal.supersessionMode !== 'replace') throw Error('negative signal cannot supersede with this mode'); }
  async activeSignals() { const reviews = await this.all('reviews'); const accepted = reviews.filter(r => r.decision === 'accept').map(r => r.signal); const retired = new Set(accepted.filter(s => s.supersessionMode !== 'narrow').flatMap(s => s.supersedesSignalIds)); return accepted.filter(s => !retired.has(s.signalId)); }
}
